name: "Pull Request Check"

on:
  pull_request:
    types: [opened]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -E -b html -D language=fa . _build"
        docs-folder: "docs/"
